### ISSUE TITLE
这个项目是干啥的呀，嘿嘿

### ISSUE THREAD

**Issue by yushuai** [duochirou/CAS-SIAT-BMI#1]

**Comment by duochirou** [comment]
杨敏姐让我把数据传上去




| |
李保成
邮箱：15201501314@163.com
|

签名由 网易邮箱大师 定制

在2018年02月02日 11:20，Shuai Yu 写道：

**Comment by yushuai** [comment]
还可以用邮箱回issue呐~~

**Comment by duochirou** [comment]
老高端了.
